### PR TITLE
Apply black and other fixes

### PR DESCRIPTION
**Pull request by Seanny123**
As described in the commit history, this PR:

1. Apply `black` to all files
2. Fix some type errors in tests
3. Order and fix imports in `evaluation.py`
4. Add some missing type annotations

Addresses #19 and #22

### CODE REVIEW

**Comment by Seanny123** [comment]
This PR has been rebased and is ready for review.

**Comment by clauswilke** [comment]
I'm sorry, I'm not comfortable merging this as is, because it does two things at the same time: (i) apply styling throughout the code base; (ii) make various other improvements to the code. I think these need to be separated out.

I propose the following, which should be the simplest way forward:

1. Keep this PR active for now.
2. Do a clean checkout of the current master, apply black, and then make a PR based on just this one set of changes.
3. I merge the styling PR.
4. Then, you rebase this PR to the latest master so this becomes exclusively a code improvement PR.

**Comment by clauswilke** [comment]
Can we close this PR?

**Comment by Seanny123** [comment]
Yes, I'll close it, but please don't delete it yet. I may need to consult it in the near future.

**Pull request closed without merging**
