### PR TITLE
Type annotations

### LINKED ISSUE #20: Add type annotations
Allows for easier interfacing and debugging

### PR DESCRIPTION
**Pull request by Seanny123**
Added type annotations to make refactoring, documentation and usage easier. Resolves #20

### CODE REVIEW

**Comment by Seanny123** [comment]
@mtien this is now ready for review and discussion. If you have any questions about the changes I made, I would be happy to discuss them here or via video chat.

**Comment by mtien** [comment]
I am not familiar with the changes between python versions. If this makes the code run in the lastest release of python then I have nothing to discuss.

**Comment by clauswilke** [comment]
@Seanny123 I'm also not familiar with the constructs you're using here. Could you point me to a brief tutorial or other documentation so I can read up on it?

As an aside, if you're motivated to do this work: I think we need some real unit tests and hook them up to continuous integration so we can feel more confident in merging PRs. From a software engineering perspective, the correct order of things would be to set up the CI first and only then start making larger changes to the code.

**Comment by Seanny123** [comment]
The code already runs in the most recent of Python and this pull-request does not change any runtime behaviour.

What it does is allow for type-checking using `mypy` or `pyright`. This tutorial goes through the basics of [type-checking](https://realpython.com/python-type-checking/) and how it integrates with editors to catch more static errors before running/testing the code.

I do think adding unit tests would be helpful. Unfortunately, I'm not familiar enough with the biological principles to write reasonable unit-tests.

**Comment by clauswilke** [comment]
Ok, I've looked this over. I agree in principle but let me see if I can set up unit tests first. Shouldn't be that hard.

**Comment by Seanny123** [comment]
FYI, if you are going to write unit-tests, I would recommend using `pytest` instead of the built-in Python `UnitTest` module.

**Comment by clauswilke** [comment]
@Seanny123 I have now set up a testing infrastructure that makes me more comfortable to review PRs such as this one. Could you update to the latest code base? (Note we moved the repo under my name, https://github.com/clauswilke/PeptideBuilder/)

Also, if you happen to have any insight into why code coverage [comes out at 0%](https://codecov.io/github/clauswilke/PeptideBuilder?branch=master), that would be appreciated. Coverage is calculated correctly on my local machine but fails on Travis (all numbers are 0), so I have no idea how to debug this.

**Comment by Seanny123** [comment]
Luckily, this code has not been affected by any of the changes, so it is ready for review without further modification.

Unfortunately, I'm not familiar with getting code coverage registered by TravisCI.

**Comment by clauswilke** [comment]
I need at least one additional commit to trigger the automated tests. If you can merge in the current master and push that should suffice. (Rebase is not needed.)

**Comment by Seanny123** [comment]
Sorry for misunderstanding your request. I have brought this branch up-to-date with your masster.

**Comment by clauswilke** [comment]
It looks like Travis runs are currently not working. I'll ping you when things are working properly again.

**Comment by clauswilke** [comment]
Travis seems to be working again. However, because your PR was created before I set up CI, it looks like it didn't check this one properly. I'm going to close this PR. Please open a new one.

**Pull request closed without merging**
